name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install dependencies
        run: npm install

      - name: Expo Prebuild
        run: npx expo prebuild --platform android --clean

      - name: Grant execute permission for gradlew
        run: chmod +x android/gradlew

      - name: Build Android Release APK
        env:
          JAVA_HOME: ${{ env.JAVA_HOME_17_X64 }}
        run: |
          cd android
          ./gradlew assembleRelease --no-daemon -Dorg.gradle.java.home="${{ env.JAVA_HOME_17_X64 }}"

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Salaty-v1.0.6
          path: android/app/build/outputs/apk/release/*.apk
